name: cv_responsive
description: CV responsive.
publish_to: 'none'
version: 0.0.7-beta+7

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_launcher: ^6.3.0 #https://pub.dev/packages/url_launcher
  font_awesome_flutter: ^10.1.0 #https://pub.dev/packages/font_awesome_flutter
  simple_animation_progress_bar: 1.8.2 #https://pub.dev/packages/simple_animation_progress_bar
  flutter_svg: ^1.1.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  intl: ^0.19.0 #https://pub.dev/packages/intl
  in_app_update: ^4.2.3 #https://pub.dev/packages/in_app_update
  stacked_generator: ^1.3.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/photo.png
    - images/flags/
    - images/icons/
flutter_intl:
  enabled: true